name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Go 1.24
    - name: Set up Go 1.24
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    # Step 3: Install dependencies (if needed)
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Run build or test
    - name: Build the project
      run: |
        npm run build
